---
title: "VRCC Analysis - Testing"
author: "AM, FK, PM"
date: "May 5, 2019"
# contact: "klotzsche@cbs.mpg.de", "aleksander.molak@gmail.com", "pawel.motyka@psych.uw.edu.pl"
output: html_document
chunk_output_type: console
self_contained: no
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
basic_color <- '#195e8c'
```

# Import libraries & setup directories & read the data

```{r message=FALSE, warning=FALSE}

# Utils
library(dplyr) 
library(here)
library(tidyr)

# Plotting and tables
library(ggplot2)
library(sjPlot)
library(gghalves)
library(scales)

# Statistical tools
library(lme4)
library(lmtest)
library(lmerTest)
library(car)
library(BayesFactor)
library(effsize)
library(psych)


# Set up the fulldata directory
VRCC_dir         <- here()
# Read the preprocessed data
data <- read.csv(file = paste0(VRCC_dir,"/Data/VRTask/VRCC_data_consolidated"))

# convert distances from m to cm
data <- data %>%
mutate(EstimatedDistance = EstimatedDistance * 100, RealDistance = RealDistance * 100, DistanceError = DistanceError * 100 , DistanceErrorAbs = DistanceErrorAbs * 100, LocalizationError = LocalizationError * 100)

#### Everything below to be replaced by reading the prepared file (yet saving created some problems - some unusal structure @Aleksander's help there much appreciated)
source(here("./Code/Analyses/VRTask/Utils/read_utils.r"))
qstnr_data_path  <- here("./Data/VRTask/Ratings/Ratings_cleaned_AM_2020_10_20.xlsx")
sess_info_folder <- here('./Data/VRTask/Logfiles/ExpSubjects')

q_data <- get_questnr_data(qstnr_data_path, sess_info_folder)
length(unique(q_data$subject))
# # Drop unused data from five subjects
pre_exclusions <- c("S11", "S13", "S18", "S21", "S44")
q_data <- q_data[!(q_data$subject %in% pre_exclusions), ]
length(unique(q_data$subject))


```

<br>

# Subjective ratings (first at full visibility) and Distance Error

```{r warning=FALSE}

q_data$round_info[is.na(q_data$round_info), ] <- "Subj_ratings"

q <- q_data[q_data$round_info == "Subj_ratings",]


length(unique(q$subject))

q <- plyr::rename(q, replace = c("subject" = "ID"))
q <- plyr::rename(q, replace = c("animal" = "Stimulus"))

d <- data %>% 
  group_by(ID, Stimulus) %>%
  summarize(distance_error  = mean(DistanceError), distance_error_norm  = mean(DistanceErrorNorm))

dt <- merge(q, d, by = c("ID", "Stimulus"))
length(unique(dt$ID))

# THREAT: DISTANCE ERROR (cm)
for (s in unique(dt$Stimulus)) {

  ds <- dt[dt$Stimulus == s,]  

cor <- cor.test(ds$threat, ds$distance_error, method = "spearman")
rho <- round(cor$estimate, digits = 3)
p_val <- round(cor$p.value, digits = 3)

scatter.smooth(ds$threat, ds$distance_error, main = paste0(s, "\n(rho = ", rho, ", p = ",p_val,")"), pch = 20, cex = 2, col = scales::alpha("firebrick",0.5), lwd = 2, xlim = c(1,7), ylim = c(-105,105))
}

# THREAT: DISTANCE ERROR NORM (%)
for (s in unique(dt$Stimulus)) {
  
ds <- dt[dt$Stimulus == s,]  

cor <- cor.test(ds$threat, ds$distance_error_norm, method = "spearman")
rho <- round(cor$estimate, digits = 3)
p_val <- round(cor$p.value, digits = 3)

scatter.smooth(ds$threat, ds$distance_error_norm, main = paste0(s, "\n(rho = ", rho, ", p = ",p_val,")"), pch = 20, cex = 2, col = scales::alpha("firebrick",0.5), lwd = 2, xlim = c(1,7), ylim = c(-35,35))
}



# DISGUST: DISTANCE ERROR (cm)
for (s in unique(dt$Stimulus)) {
  
ds <- dt[dt$Stimulus == s,]  

cor <- cor.test(ds$disgust, ds$distance_error, method = "spearman")
rho <- round(cor$estimate, digits = 3)
p_val <- round(cor$p.value, digits = 3)

scatter.smooth(ds$disgust, ds$distance_error, main = paste0(s, "\n(rho = ", rho, ", p = ",p_val,")"), pch = 20, cex = 2, col = scales::alpha("#66804d",0.5), lwd = 2, xlim = c(1,7), ylim = c(-105,105))

}

# DISGUST: DISTANCE ERROR NORM (%)
for (s in unique(dt$Stimulus)) {
  
ds <- dt[dt$Stimulus == s,]  

cor <- cor.test(ds$disgust, ds$distance_error_norm, method = "spearman")
rho <- round(cor$estimate, digits = 3)
p_val <- round(cor$p.value, digits = 3)

scatter.smooth(ds$disgust, ds$distance_error_norm, main = paste0(s, "\n(rho = ", rho, ", p = ",p_val,")"), pch = 20, cex = 2, col = scales::alpha("#66804d",0.5), lwd = 2, xlim = c(1,7), ylim = c(-35,35))

}


# SPEED: DISTANCE (cm)
for (s in unique(dt$Stimulus)) {
  
ds <- dt[dt$Stimulus == s,]  

cor <- cor.test(ds$how_fast, ds$distance_error, method = "spearman")
rho <- round(cor$estimate, digits = 3)
p_val <- round(cor$p.value, digits = 3)

scatter.smooth(ds$how_fast, ds$distance_error, main = paste0(s, "\n(rho = ", rho, ", p = ",p_val,")"), pch = 20, cex = 2, col = scales::alpha("royalblue",0.6), lwd = 2, xlim = c(1,7), ylim = c(-110,110))
}

# SPEED: DISTANCE NORM (%)
for (s in unique(dt$Stimulus)) {
  
ds <- dt[dt$Stimulus == s,]  

cor <- cor.test(ds$how_fast, ds$distance_error_norm, method = "spearman")
rho <- round(cor$estimate, digits = 3)
p_val <- round(cor$p.value, digits = 3)

scatter.smooth(ds$how_fast, ds$distance_error_norm, main = paste0(s, "\n(rho = ", rho, ", p = ",p_val,")"), pch = 20, cex = 2, col = scales::alpha("royalblue",0.6), lwd = 2, xlim = c(1,7), ylim = c(-35,35))
}



```

ANOVA

```{r}

d <- dt[dt$fear_object == "True",]
d <- d %>% 
  group_by(ID) %>%
  summarize(distance_error  = mean(distance_error), distance_error_norm  = mean(distance_error_norm), threat = mean(threat), disgust = mean(disgust))

scatter.smooth(d$threat, d$distance_error, span = 1)
cor.test(d$threat, d$distance_error, method = "pearson")
scatter.smooth(d$disgust, d$distance_error, span = 1)
cor.test(d$disgust, d$distance_error, method = "pearson")

scatter.smooth(d$threat, d$disgust)
shapiro.test(d$threat)
cor.test(d$threat, d$disgust, method = "spearman")
               
mT <- mean(d$threat)
sdT <- sd(d$threat)
mD <- mean(d$disgust)
sdD <- sd(d$disgust)

d$threat_z <- (d$threat - mT) / sdT
d$disgust_z <- (d$disgust - mD) / sdD

# earlier I tried with 1SD (as in work by Cole et al.) but almost no observations extracted 
highT_highD <- median(d$distance_error[d$threat_z > 0 & d$disgust_z > 0])
lowT_lowD <- median(d$distance_error[d$threat_z < -0 & d$disgust_z < -0])
highT_lowD <-  median(d$distance_error[d$threat_z > 0 & d$disgust_z < -0])
low_T_highD <- median(d$distance_error[d$threat_z < -0 & d$disgust_z > 0])

low_disgust <- c(lowT_lowD, highT_lowD)
high_disgust <- c(low_T_highD, highT_highD)

# Graph cars using a y axis that ranges from 0 to 12
plot(high_disgust, type="o", col="black", ylim=c(-15,10))

# Graph trucks with red dashed line and square points
lines(low_disgust, type="o", pch=22, lty=2, col="black")


for (s in unique(dt$Stimulus)) {
  
ds <- dt[dt$Stimulus == s,]  

cor <- cor.test(ds$threat, ds$disgust, method = "spearman")
rho <- round(cor$estimate, digits = 3)
p_val <- round(cor$p.value, digits = 3)

scatter.smooth(ds$threat, ds$disgust, main = paste0(s, "\n(rho = ", rho, ", p = ",p_val,")"), pch = 20, cex = 2, col = scales::alpha("gray40",0.6), lwd = 2, xlim = c(1,7), ylim = c(1,7))
}



```


