---
title: VRCC behavioral data
author: "PM & FK"
contact: "pawel.motyka@psych.uw.edu.pl"
date: "15th January 2019"
output: md_document
editor_options: 
chunk_output_type: console
self_contained: no
---

**1. Preprocess behavioral data**


```{r}

# send me to VRCC dir:
VRCC_dir <- "C:/Users/x220t/Seafile/CentralKollegs18/centralkollegs18"

# Set up the data directory
#data_dir <- 'N:/VRCC'
data_dir <- file.path(VRCC_dir, "Data/VRTask")
setwd(data_dir)

require(ggplot2)
require(plyr)

### Pilot 2 ###

data <- read.table(file.path(data_dir, "VRCC_pilot2.txt"), skip = 6, header = T, sep = ";", na.string ="-1")
#data <- read.table("VRCC_pilot_pawel.txt", skip = 6, header = T, sep = ";", na.string ="-1")


data$Stimulus <- as.factor(data$isFearObject)
data$Stimulus <- revalue(data$Stimulus, c("True"="Threatening", "False"="Non-threatening"))
# 
# true_est <- ggplot(data=data, aes(x=trueDistance, y=estDistance)) +
#   geom_smooth(method = "loess", level=0.95, alpha = 0.2) + geom_point(col = "black")+ scale_fill_manual() + theme_classic() + labs(x = "True distances" , y = "Estimated distances") + scale_x_continuous(limits = c(1.8, 6.5)) + scale_y_continuous(limits = c(1.8, 6.5))


## MAIN PLOT
colorset <- c("dodgerblue3", "firebrick2")

object_condition <- ggplot(data=data, aes(x=trueDistance, y=estDistance, group = Stimulus)) + geom_abline(intercept = 0, linetype = "dashed") + geom_smooth(aes(color=Stimulus), method = "loess", level=0.95, alpha = 0.2) + geom_point(aes(color=Stimulus), alpha = 0.5) + theme_classic() + labs(x = "True distance" , y = "Estimated distance") + scale_x_continuous(limits = c(1.8, 7)) + scale_y_continuous(limits = c(1.8, 7))  + theme(legend.text = element_text(size = 13), legend.position=c(0.8, 0.2), axis.text=element_text(size=14), axis.title=element_text(size=14)) + scale_colour_manual(values = colorset) 

# warning is due to x and y limits and outliers beyond and one NA in datatable
object_condition


## Error at different distances

# Absolute difference
data$diff <- data$estDistance - data$trueDistance

error <- ggplot(data=data, aes(x=trueDistance, y=diff)) +
  geom_smooth(method = "loess", level=0.95, alpha = 0.2) + geom_point(col = "black")+ scale_fill_manual() + theme_classic() + labs(x = "True distances (m)" , y = "Absolute error (m)") + scale_x_continuous(limits = c(2, 6)) + scale_y_continuous(limits = c(-4, 4))

error + geom_hline(yintercept=0, linetype="dashed", color = "red")

# Proportional difference %

data$diff_norm <- (data$diff / data$trueDistance) * 100 


error <- ggplot(data=data, aes(x=trueDistance, y=diff_norm)) +
  geom_smooth(method = "loess", level=0.95, alpha = 0.2) + geom_point(col = "black")+ scale_fill_manual() + theme_classic() + labs(x = "True distances (m)" , y = "Error in proportion to true distance (%)") + scale_x_continuous(limits = c(1.8, 6.2)) + scale_y_continuous(limits = c(-50, 100))

error + geom_hline(yintercept=0, linetype="dashed", color = "red")


## Error at different distances accounting for different objects 

# Absolute difference
object_condition <- ggplot(data=data, aes(x=trueDistance, y=diff, group= Stimulus)) +
  geom_smooth(aes(linetype=Stimulus, color=Stimulus), method = "loess", level=0.95, alpha = 0.2) + geom_point(aes(color=Stimulus))+ scale_fill_manual() + theme_classic() + labs(x = "True distances" , y = "Absolut Error") 

object_condition  + geom_hline(yintercept=0, linetype="dashed", color = "black")

# Proportional error

object_condition <- ggplot(data=data, aes(x=trueDistance, y=diff_norm, group= Stimulus)) +
  geom_smooth(aes(linetype=Stimulus, color=Stimulus), method = "loess", level=0.95, alpha = 0.2) + geom_point(aes(color=Stimulus))+ scale_fill_manual() + theme_classic() + labs(x = "True distances" , y = "Proprtional error %") 

object_condition  + geom_hline(yintercept=0, linetype="dashed", color = "black")





### Pilot 3 ###

data <- read.table(file.path(data_dir, "VRCC_pilot3.txt"), skip = 6, header = T, sep = ";", na.string ="-1.00")
data <- data[data$Phase == "Estimation",]

colnames(data)[6] <- "Animal"
colnames(data)[7] <- "Stimulus"
colnames(data)[9] <- "trueDistance"
colnames(data)[10] <- "estDistance"

data$Stimulus <- revalue(data$Stimulus, c("True"="Threatening", "False"="Non-threatening"))

data$estDistance <- as.numeric(as.character(data$estDistance))
typeof(data$estDistance)

data$trueDistance <- as.numeric(as.character(data$trueDistance))
typeof(data$trueDistance)


data$trueDistance <- as.numeric(data$trueDistance - 7)



## MAIN PLOT
colorset <- c("dodgerblue3", "firebrick2")

object_condition <- ggplot(data=data, aes(x=trueDistance, y=estDistance, group = Stimulus)) + geom_abline(intercept = 0, linetype = "dashed") + geom_smooth(aes(color=Stimulus), method = "loess", level=0.95, alpha = 0.2) + geom_point(aes(color=Stimulus), alpha = 0.5) + theme_classic() + labs(x = "True distance" , y = "Estimated distance") + scale_x_continuous(limits = c(1.8, 7)) + scale_y_continuous(limits = c(1.8, 7))  + theme(legend.text = element_text(size = 13), legend.position=c(0.8, 0.2), axis.text=element_text(size=14), axis.title=element_text(size=14)) + scale_colour_manual(values = colorset) 

# warning is due to x and y limits and outliers beyond and one NA in datatable
object_condition


## Error at different distances

# Absolute difference
data$diff <- data$estDistance - data$trueDistance

error <- ggplot(data=data, aes(x=trueDistance, y=diff)) +
  geom_smooth(method = "loess", level=0.95, alpha = 0.2) + geom_point(col = "black")+ scale_fill_manual() + theme_classic() + labs(x = "True distances (m)" , y = "Absolute error (m)") + scale_x_continuous(limits = c(2, 6)) + scale_y_continuous(limits = c(-4, 4))

error + geom_hline(yintercept=0, linetype="dashed", color = "red")

# Proportional difference %

data$diff_norm <- (data$diff / data$trueDistance) * 100 


error <- ggplot(data=data, aes(x=trueDistance, y=diff_norm)) +
  geom_smooth(method = "loess", level=0.95, alpha = 0.2) + geom_point(col = "black")+ scale_fill_manual() + theme_classic() + labs(x = "True distances (m)" , y = "Error in proportion to true distance (%)") + scale_x_continuous(limits = c(1.8, 6.2)) + scale_y_continuous(limits = c(-50, 100))

error + geom_hline(yintercept=0, linetype="dashed", color = "red")


## Error at different distances accounting for different objects 

# Absolute difference
object_condition <- ggplot(data=data, aes(x=trueDistance, y=diff, group= Stimulus)) +
  geom_smooth(aes(linetype=Stimulus, color=Stimulus), method = "loess", level=0.95, alpha = 0.2) + geom_point(aes(color=Stimulus))+ scale_fill_manual() + theme_classic() + labs(x = "True distances" , y = "Absolut Error") 

object_condition  + geom_hline(yintercept=0, linetype="dashed", color = "black")

# Proportional error

object_condition <- ggplot(data=data, aes(x=trueDistance, y=diff_norm, group= Stimulus)) +
  geom_smooth(aes(linetype=Stimulus, color=Stimulus), method = "loess", level=0.95, alpha = 0.2) + geom_point(aes(color=Stimulus))+ scale_fill_manual() + theme_classic() + labs(x = "True distances" , y = "Proprtional error") 

object_condition  + geom_hline(yintercept=0, linetype="dashed", color = "black")

```

```{r, opts, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "images/"
)

require(dplyr)

# Start here with DF "data" from above (after inital processing):

# drop unnecessary factor levels:
data <- droplevels(data)

# remove trials with incomplete data in relevant domains:
data <- data[complete.cases(data[, c('Stimulus', 'estDistance', 'trueDistance')]), ]

# calculate relation of estDist to trueDist:
data$rel <- data$estDistance/data$trueDistance

# let's permute:
anims <- levels(data$Animal)

n_reps = 300
res <- NULL
res2 <- NULL
ans <- NULL

for (rep in 1:n_reps) {
  
  c1 <- sample(anims, 4)
  data$NewStimulus <- "NonThreatening"
  data$NewStimulus[is.element(data$Animal, c1)] <- "Threatening"
  relTT <- t.test(rel ~ NewStimulus, data = data)
  
  #if ((relTT$p.value < 0.005) && (relTT$estimate[1] > relTT$estimate[2])) {
  if (relTT$statistic > 3.9) {
    res <- append(res, relTT$estimate[2])
    res2 <- append(res, relTT$estimate[1])
    ans <- append(ans, c1)}
}
ansf <- as.factor(ans)
summary(ansf)
hist(res)  

# summarize to get mean per condition: 
meansStim <- data %>% group_by(Stimulus) %>% summarise(mean = mean(rel))

meansAnim <- data %>% group_by(stimulus) %>% summarise(mean = mean(rel), sd = sd(rel))

# histogram:
relHist <- ggplot(data, aes(x = rel, fill = Stimulus)) + 
  geom_histogram(binwidth = 0.01, position = "identity", alpha = 0.5) + 
  xlim(0.5, 1.5)  +
  geom_density(alpha = 0.2) +
  geom_vline(data=meansStim, aes(xintercept = mean, color = Stimulus), 
             linetype = 'dashed', size = 1) +
  scale_fill_manual(values = c('blue', 'red')) + 
  scale_color_manual(values = c('blue', 'red')) +
  labs(x = "estimated dist. / true dist.") + 
  theme_classic()
    
  
relHist

# T-Test:
relTT <- t.test(rel ~ Stimulus, data = data)
relTT
```




```{r}
require(ggplot2)
require(plyr)
require(dplyr)
require(lmtest)

# Load both data sets:

# send me to VRCC dir:
VRCC_dir <- "C:/Users/x220t/Seafile/CentralKollegs18/centralkollegs18"

# Set up the data directory
#data_dir <- 'N:/VRCC'
data_dir <- file.path(VRCC_dir, "Data/VRTask/")
setwd(data_dir)
dat <- NULL
data <- NULL

### Pilot 2 ###
dat <- read.table(file.path(data_dir, "VRCC_pilot2.txt"), skip = 6, 
                        header = T, sep = ";", na.string ="-1")

# cut to relevant columns:
dat <- dat[ , c("stimulus", "isFearObject", "estDistance", 
                            "trueDistance")]
colnames(dat) <- c("Animal", "isFear", "estDist", "trueDist")

dat <- dat[complete.cases(dat), ]

dat$Animal <- as.factor(gsub(pattern = " \\(UnityEngine.GameObject\\)", 
                   replacement = '', 
                   dat$Animal))
dat$isFear <- as.logical(dat$isFear)

# save to list:
dat$who <- as.factor("P01")
data[[1]] <- dat 
dat <- NULL



### Pilot 3 ###

dat <- read.table(file.path(data_dir, "VRCC_pilot3.txt"), skip = 6, header = T, sep = ";", na.string ="-1.00")
dat <- dat[dat$Phase == "Estimation",]

dat <- dat[ , c(6,7,10,9)]
colnames(dat) <- c("Animal", "isFear", "estDist", "trueDist")

# drop unnecessary factor levels:
dat <- droplevels(dat)

# remove trials with incomplete data in relevant domains:
dat <- dat[complete.cases(dat), ]

# get types right and correct trueDist for offset of playerPos:
dat$isFear <- as.logical(dat$isFear)
dat$estDist <- as.numeric(as.character(dat$estDist))
dat$trueDist <- as.numeric(as.character(dat$trueDist)) - 7

# save to list:
dat$who <- as.factor("P02")
data[[2]] <- dat 
dat <- NULL

# merge data sets:
fulldat <- rbind(data[[1]], data[[2]])

# calculate relation of estDist to trueDist:
fulldat$rel <- fulldat$estDist/fulldat$trueDist

# calc. error:
fulldat <- fulldat %>% mutate(err = (estDist - trueDist),
                              errAbs = abs(err),
                              errNorm = err/trueDist,
                              errAbsNorm = abs(errNorm))

meansStim <- fulldat %>% 
  filter(who == "P02") %>%
  group_by(isFear) %>% 
  summarise(meanRel = mean(rel), 
            meanErr = mean(errNorm),
            meanErrAbs = mean(errAbsNorm))

meansAnim <- fulldat %>% 
  filter(who == "P02") %>%
  group_by(Animal) %>% 
  summarise(meanRel = mean(rel), 
            meanErr = mean(errNorm),
            meanErrAbs = mean(errAbsNorm))



p1dat <- fulldat %>%
  filter(who == "P01")

p2dat <- fulldat %>%
  filter(who == "P02")

lmErrDist <- lm(err~trueDist, data = p2dat)
plot(lmErrDist)

# studentized Breusch-Pagan test to test for homoscedasticity:
bptest(lmErrDist)

plot(err ~ trueDist, data = p1dat)

```


